# spring.application.name=PR_BackEnd

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PR?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ohoh7920
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  secret: 1e8e778610b669ee0a38e40dcef5209ccd62b4e374e3807aa83ecead679ea729

logging:
  level:
    org:
      springframework:
        security: DEBUG